---
# yaml-language-server: $schema=https://home-kubernetes-schemas.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: &app dragonfly
spec:
  selector:
    matchLabels:
      app: *app
  podTargetLabels: ["app"]
  podMetricsEndpoints:
    - port: admin
