---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ingress
spec:
  hostname: homelab-ingress
  subnetRouter:
    advertiseRoutes:
      - 192.168.1.1/32
      - 192.168.20.0/24
      - 192.168.30.0/24
